country_to_continent = {
    'Chile': 'South America',
    'Italy': 'Europe',
    'United States of America': 'North America',
    'Russia': 'Europe',
    'El Salvador': 'North America',
    'Ecuador': 'South America',
    'Indonesia': 'Asia',
    'Philippines': 'Asia',
    'France': 'Europe',
    'Iceland': 'Europe',
    'Costa Rica': 'North America',
    'Papua New Guinea': 'Oceania',
    'India': 'Asia',
    'Vanuatu': 'Oceania',
    'Colombia': 'South America',
    'Japan': 'Asia',
    'Spain': 'Europe',
    'Northern Mariana Islands': 'Oceania',
    'Nicaragua': 'North America',
    'Saint Vincent and the Grenadines': 'North America',
    'Peru': 'South America',
    'Mexico': 'North America',
    'Democratic Republic of the Congo': 'Africa',
    'United Republic of Tanzania': 'Africa',
    'South Georgia and the Islands': 'Antarctica',
    'Tonga': 'Oceania',
    'Guatemala': 'North America',
    'Cabo Verde': 'Africa',
    'New Zealand': 'Oceania',
    'Heard Island and McDonald Islands': 'Antarctica',
    'Eritrea': 'Africa',
    'Ethiopia': 'Africa',
    'Comoros': 'Africa',
    'Montserrat': 'North America',
    'South Africa': 'Africa',
    'Cameroon': 'Africa',
    'Portugal': 'Europe',
    'Dominica': 'North America',
    'Bolivia': 'South America',
    'Argentina': 'South America',
    'Iran': 'Asia',
    'Antarctica': 'Antarctica',
    'Norway': 'Europe',
    'Djibouti': 'Africa',
    'Kenya': 'Africa',
    'Saint Helena': 'Africa',
    'Rwanda': 'Africa',
    'China': 'Asia',
    'Yemen': 'Asia',
    'Equatorial Guinea': 'Africa',
    'Greece': 'Europe',
    'Samoa': 'Oceania',
    'Canada': 'North America',
    'North Korea': 'Asia',
    'Solomon Islands': 'Oceania',
    'Turkey': 'Europe/Asia',
    'Jordan': 'Asia',
    'Saint Kitts and Nevis': 'North America',
    'Saudi Arabia': 'Asia',
    'French Southern and Antarctic Lands': 'Antarctica',
    'Saint Lucia': 'North America',
    'Fiji': 'Oceania',
    'Netherlands': 'Europe',
    'Panama': 'North America',
    'South Korea': 'Asia',
    'Sudan': 'Africa',
    'Armenia': 'Asia',
    'Taiwan': 'Asia',
    'American Samoa': 'Oceania',
    'Myanmar': 'Asia',
    'Georgia': 'Europe/Asia',
    'Uganda': 'Africa',
    'Australia': 'Oceania',
    'Mongolia': 'Asia',
    'Madagascar': 'Africa',
    'Honduras': 'North America',
    'Germany': 'Europe',
}
